baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yuna Kim'
enableEmoji = true

theme = 'gokarna'

[params]

avatarAltText = "avatar"
avatarSize = "size-m"
avatarURL = "/yukino.png"

socialIcons = [
    {name = "github", url = "https://github.com/YunaCreates"},
]

[menu]

    [[menu.main]]
        name = "Home"
        pre = "ğŸ¡"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        pre = "ğŸ“œ"
        url = "/posts/"
        weight = 20
